export const tintDetailedOpeningLiteralRewrites: ReadonlyArray<
  readonly [string, string]
> = [
  ["Chapter 118 — Sudden Infant Death Syndrome（SIDS，嬰兒猝死症候群）", "Sudden Infant Death Syndrome（SIDS，嬰兒猝死症候群）"],
  ["作者提出四個評估 EMS equipment 的基本問題：", "EMS equipment 可用四個基本問題評估："],
  ["真正的臨床重點是不是「飛機是不是比較快」，而是：", "真正的臨床重點不是「飛機是不是比較快」，而是："],
  ["Vernakalant 在出版時尚未於美國上市，但已在 Canada/Europe 使用。", ""],
  ["**Air break** 可實務理解為：在維持 chamber pressure 的情況下，暫時降低吸入氧濃度或改吸 air，以限制 CNS oxygen toxicity；此概念，但未另列正式定義。", "**Air break** 是在維持 chamber pressure 的情況下，暫時降低吸入氧濃度或改吸 air，以限制 CNS oxygen toxicity。"],
  ["Figures 29A-1 至 29A-3 顯示三個實用原則：", "氣道定位可依三個實用原則調整："],
  ["傳統氣道定位會比較 oral、pharyngeal、laryngeal axes，圖中枕部約抬高 10 cm；臨床重點不是固定高度，而是依體型調整，使口咽軸線與操作者視線最佳化。", "傳統氣道定位會比較 oral、pharyngeal、laryngeal axes；枕部可先約抬高 10 cm，再依體型調整，使口咽軸線與操作者視線最佳化。"],
  ["資料顯示，peri-intubation hypotension 約 **23%**，peri-intubation cardiac arrest 約 **4%**。生理狀態不佳時，即使解剖上是「容易氣道」，仍屬於高風險插管。", "Peri-intubation hypotension 與 cardiac arrest 是重要風險；生理狀態不佳時，即使解剖上是「容易氣道」，仍屬於高風險插管。"],
  ["**考點：**接上「100% oxygen」不代表肺泡已充分預氧。", "**預氧品質：**接上「100% oxygen」不代表肺泡已充分預氧。"],
  ["重點是未分化胸痛的危險度辨識與診斷策略；ACS 的完整治療、低風險胸痛 pathway、stress testing 與 disposition 主要留在後續章節。", "未分化胸痛應先辨識 ACS 與其他致命病因，再依危險度決定檢驗、治療與 disposition。"],
  ["提出約 **2.5% pretest probability** 作為是否開始檢查的概念性門檻；", "約 **2.5% pretest probability** 可作為是否開始檢查的概念性門檻；"],
  ["上呼吸道感染還可形成 otitis media、pharyngitis、epiglottitis、sinusitis、bronchiolitis 或 tracheitis；這些疾病在其他章節分別討論。", "上呼吸道感染可能合併 otitis media、pharyngitis、epiglottitis、sinusitis、bronchiolitis 或 tracheitis；出現相應局部症狀或重症徵象時，應轉入對應的專病評估。"],
  ["未另列；治療路徑通常意味住院", "通常需住院接受引流、抗感染治療與監測"],
  ["1. 資料顯示，認為 LGIB 的發生比 upper GI bleeding 更常見，年發生率約 **109/100,000**，死亡率 **\u003c1%**。", "1. LGIB 的年發生率約 **109/100,000**，死亡率 **\u003c1%**；數值應與資料年代及研究母群一併解讀。"],
  ["* Cross-sectional imaging 與 high-definition US 的使用量雖增加超過一倍，章節所引資料顯示 appendicitis detection rate 並未明顯改善，說明影像不能取代臨床推理。", "* Cross-sectional imaging 與 high-definition US 可協助診斷，但影像不能取代臨床推理。"],
  ["**Intestinal pseudo-obstruction（Ogilvie syndrome）** 可模仿機械性阻塞；需注意要納入鑑別，但未另行詳述其治療。", "**Intestinal pseudo-obstruction（Ogilvie syndrome）** 可模仿機械性阻塞，應依大腸擴張程度、缺血／穿孔風險與病因處置。"],
  ["Closed-loop obstruction 的近端與遠端皆被封閉，腸內容物無法向任何方向減壓，因此缺血與壞死進展較快。舉出的例子包括：", "Closed-loop obstruction 的近端與遠端皆被封閉，腸內容物無法向任何方向減壓，因此缺血與壞死進展較快；常見情境包括："],
  ["此處僅概述significant GU trauma；完整處置在 Chapter 265。兒童／青少年 GU emergencies 主要見 Chapter 136；urethritis 見 Chapter 153；urethral stricture 所致 retention 見 Chapter 92。", ""],
  ["考試可記憶，實際臨床則應以現行 NRP、當地 NICU／perinatal-center protocol 與個案 shared decision 為準。", "新生兒復甦應依現行 NRP、區域 NICU／perinatal-center protocol 與個案 shared decision 執行。"],
  ["非頸椎部位的兒童脊椎與脊髓傷害則另見 Chapter 110。", "非頸椎部位的兒童脊椎與脊髓傷害亦應依完整創傷流程評估。"],
  ["以下是整合的實用選擇架構，不是正式的 validated decision rule。", "可依時間敏感性、周邊靜脈取得難度、輸注內容、監測需求、使用時間與操作者熟練度選擇通路。"],
  ["當時資料顯示，SUID 尚未列入 ICD-10；這是當時的編碼限制，不影響其作為 ED 描述性術語的臨床價值。", "SUID 是急診可使用的描述性術語；最終分類需整合 death-scene investigation、autopsy 與完整 clinical history。"],
  ["* **0–28 days**：最高風險；正文討論部分研究時也使用 0–30 days。舊 low-risk criteria 仍可能漏診 SBI，最安全的處置是完整 sepsis evaluation、住院、經驗性抗生素。", "* **0–28 days**：最高風險；即使外觀良好，low-risk criteria 仍可能漏診 SBI，通常需完整 sepsis evaluation、住院與經驗性抗生素。"],
  ["Figures 141-2～141-6 依序顯示 distal tibial SH-I、SH-II 的 lateral film 與 CT、SH-III Tillaux fracture，以及 SH-IV 合併 fibular SH-I。SH-II 可出現 dorsal epiphyseal displacement 並需要 reduction；骨折線可同時通過 physis 與 metaphysis。", "Distal tibial SH-I～IV 的骨折路徑依序涉及 physis、metaphysis 與 epiphysis；SH-II 可出現 dorsal epiphyseal displacement 並需要 reduction，骨折線可同時通過 physis 與 metaphysis。"],
  ["**Tillaux fracture 應理解為 distal tibia anterolateral SH-III transitional fracture。**Tillaux fracture 是 distal tibia anterolateral SH-III transitional fracture。****", "**Tillaux fracture 是 distal tibia anterolateral SH-III transitional fracture。**"],
  ["Figures 141-7、141-8、141-9 分別顯示 torus、greenstick 與 plastic deformation。bowing injury 可與另一根骨的 complete fracture 或 joint dislocation 同時存在；漏診可能留下永久變形與功能障礙。", "Torus、greenstick 與 plastic deformation 是兒童常見的不完全骨折型態；bowing injury 可與另一根骨的 complete fracture 或 joint dislocation 同時存在，漏診可能留下永久變形與功能障礙。"],
  ["**HbSC、HbS/HbO、HbS/β-thalassemia** | 嚴重度不一，部分可接近 HbSS。大多數 HbS/β-thalassemia 患者——約 90% 的概述——仍有部分正常 β-chain 產生，整體缺血與感染併發症較 HbSS 少。", "**HbSC、HbS/HbO、HbS/β-thalassemia** | 嚴重度不一；HbS/β-thalassemia 的正常 β-chain 產生量與臨床嚴重度依 genotype 而異，部分病例可接近 HbSS。"],
  ["以美國情境指出，新生兒篩檢敏感度與特異度均高，因此初次診斷很少在急診完成；急診的真正任務是辨識併發症。", "在實施新生兒篩檢的地區，SCD 通常可於症狀前辨識；急診的主要任務是辨認急性併發症。"],
  ["視為高危重症；此處僅概述，未提供完整 HHS protocol", "視為高危重症；立即評估 hyperosmolality、重度脫水、電解質缺損與神經狀態"],
  ["Gestational diabetes 亦可能涉及懷孕青少年及 diabetic mother 的嬰兒，但。", "Gestational diabetes 也可能發生於懷孕青少年，並影響 diabetic mother 的嬰兒。"],
  ["這些疾病並非全部在逐一提供專病治療；共同重點仍是**醫療穩定、安全評估、病因排除與資源銜接**。", "共同急診重點是**醫療穩定、安全評估、器質性與毒物病因排除，以及可落實的資源銜接**。"],
  ["圖 152-1 特別提醒：**外觀看到的紅斑可能遠小於深層實際受侵犯範圍**。", "**外觀看到的紅斑可能遠小於深層實際受侵犯範圍。**"],
  ["以下為急診整合架構，並非正式 clinical decision rule。", "可依六種不能延誤的臨床情境進行分流。"],
  ["對 suspected VHF 採 建議，包括 negative-pressure room、respiratory protection、gown 與 gloves；實務須依當前病原及院內 PPE protocol 調整。", "Suspected VHF 應立即採取適用的 isolation 與 PPE，包括 negative-pressure room、respiratory protection、gown 與 gloves，並依當前病原及院內 protocol 調整。"],
  ["足量使用兩種 IV antiseizure agents 後仍持續發作；另有資料稱通常已超過 60 分鐘，但治療上不可等待 60 分鐘才升級", "足量使用兩種 IV antiseizure agents 後仍持續發作；治療不可等待固定時長才升級"],
  ["**考試最重要的第一句：MAOI overdose 具有延遲毒性。前幾小時無症狀，不能視為安全。**", "**MAOI overdose 具有延遲毒性；前幾小時無症狀也不能視為安全。**"],
  ["臨床上可能出現兩種看似矛盾、卻極具考試價值的情況：", "臨床上可能出現兩種看似矛盾但重要的情況："],
  ["正文指出，alprazolam、temazepam、triazolam 等高效價、較短作用藥物", "Alprazolam、temazepam、triazolam 等高效價、較短作用藥物"],
  ["β-blockers 與 calcium channel blockers 分別見 Chapters 194、195。", ""],
  ["沒有獨立影像、ECG 或正式流程圖，核心視覺資料為 **Tables 197-1 至 197-5**。", ""],
  ["* Clonazepam、clobazam 的毒性屬 benzodiazepine toxicology，另見 Chapter 183。", "* Clonazepam、clobazam 應按 benzodiazepine toxicity 評估與處置。"],
  ["Water-soluble 並非保證安全；**niacin、pyridoxine 與 ascorbate**。", "Water-soluble 並非保證安全；**niacin、pyridoxine 與 ascorbate** 在高劑量或高風險宿主中也可能造成顯著毒性。"],
  ["* Vitamin C 與 glutathione 僅參與很有限的 nonenzymatic reduction；目前沒有提供將 vitamin C 作為主要急診 antidote 的劑量。", "* Vitamin C 與 glutathione 僅參與有限的 nonenzymatic reduction，不能取代標準 antidotal therapy。"],
  ["若 1 小時後 cyanosis 尚未清除，可接受 repeat dosing；但**沒有提供 cumulative maximum 或無限制重複給藥的依據**，實際重複劑量須依 serial MetHb、臨床反應及 toxicology guidance。", "若 1 小時後 cyanosis 尚未清除，可考慮 repeat dosing；重複劑量須依 serial MetHb、臨床反應及 toxicology guidance，且不可無限制重複給藥。"],
  ["僅寫可使用 cimetidine 的 **standard doses**，並未提供具體 dose、route 或 duration，不應自行從推導。", "Cimetidine 可減少 active metabolite formation，但沒有足以支持固定急診劑量的資料，應由 toxicology team 個別決定。"],
  ["許多相關藥物本身並不含 sulfur，因此 sulfur 的來源仍屬推測。章節提出，藥物改變 intestinal flora 後，可能由 **Morganella morganii** 等細菌產生 hydrogen sulfide 或 glutathione。", "許多相關藥物本身並不含 sulfur；可能機轉是藥物改變 intestinal flora 後，由 **Morganella morganii** 等細菌產生 hydrogen sulfide 或 glutathione。"],
  ["Figure 207-3 支持：", "可依 MetHb 濃度與臨床症狀分流："],
  ["但目前沒有提供固定 observation hours、serial co-oximetry interval、discharge threshold、formal admission criteria 或 follow-up schedule。尤其 **dapsone 可因約 50 小時 half-life 與 delayed active metabolite 而 rebound**，不能把單次症狀或 MetHb 改善直接等同安全離院。", "Observation 與 disposition 應依 serial co-oximetry、臨床趨勢、暴露物與 rebound risk 決定；**dapsone 可因約 50 小時 half-life 與 delayed active metabolite 而 rebound**，不能把單次症狀或 MetHb 改善直接等同安全離院。"],
  ["考場最容易錯的地方", "常見判讀陷阱"],
  ["\u003e **臨床時效提醒：** 下列 methylene blue 門檻、重複給藥、G6PD deficiency、dapsone/cimetidine 與 refractory treatment 為 Tintinalli 9e 的 source-era guidance。實際治療應同步依 poison center、medical toxicology 與機構 protocol。", "\u003e Methylene blue 門檻、重複給藥、G6PD deficiency、dapsone／cimetidine 與 refractory treatment，應依 serial MetHb、臨床反應、poison center、medical toxicology 與機構 protocol 調整。"],
  ["書中列出的藥物包括", "可考慮的藥物包括"],
  ["書中方案為", "可採用"],
  ["**原表將 20,000 ft 誤印為 7000 m；20,000 ft 實際約為 6096 m。**其血氣數值仍照原表保留。", "20,000 ft 約為 6096 m。"],
  ["**最重要的考試規則：症狀延遲超過 6 小時才出現的「腸胃炎」，不能當作單純 food poisoning。**", "**症狀延遲超過 6 小時才出現的「腸胃炎」，不能當作單純 food poisoning。**"],
  ["補充 IV fluids；若 glucose 偏低或 glycogen depletion，可用 isotonic saline with 5% dextrose。正文亦提到 5% 或 10% dextrose。", "補充 IV fluids；若 glucose 偏低或 glycogen depletion，可依血糖選擇含 5% 或 10% dextrose 的 isotonic fluid。"],
  ["正文另列 propranolol slow IV 1–2 mg，可 q10–15 min 重複至 clinical improvement 或 HR \u003c100；另列 PO 20–120 mg/次或總量 160–320 mg/day divided。這些是不同 regimen，**不可視為可任意互換的單一 protocol**。", "Propranolol 另有 slow IV 1–2 mg、可 q10–15 min 重複至 clinical improvement 或 HR \u003c100 的 regimen；PO 可用 20–120 mg/次或總量 160–320 mg/day divided。不同 regimen 不可任意互換，應依 hemodynamics 與現行 protocol 選擇。"],
  ["參考出的罕用替代包括：", "β-blocker 禁忌且無 hypotension 或明顯 CNS depression 時，可由專科評估少用的替代方案："],
  ["severe asthma 時正文特別提 2.5 mg IM q4h", "severe asthma 時可採 2.5 mg IM q4h"],
  ["\u003e **lithium 劑量內部不一致：**Table 229-7 為 300 mg PO q6h、target 約 1 mEq/L；正文為 300 mg q8h、target 0.6–1.0 mEq/L。此藥只能視為 specialist-guided alternative，不能直接產生單一醫囑。", "\u003e **Lithium 僅作 specialist-guided alternative；使用前須依最新藥典與內分泌／毒物專科建議確認劑量及 target concentration。**"],
  ["Surgery 本身可 precipitate thyroid storm。若不能延後，Table 229-8 建議快速多機轉控制：", "Surgery 本身可 precipitate thyroid storm；若不能延後，應採快速、多機轉的術前控制："],
  ["注意這裡的 iopanoic acid 是 **PO perioperative regimen**，與 storm treatment table 的 **IV regimen** 不同。", "Iopanoic acid 的 **PO perioperative regimen** 與 storm treatment 的 **IV regimen** 不可混用。"],
  ["舊式 FDA pregnancy-category C／D 敘述；考試與臨床應記住實際 trimester-specific risk，而不要把舊分類當成現行制度。", "舊式 FDA pregnancy category C／D 已不再作為現行用藥分類；應依 trimester-specific risk 選藥。"],
  ["考前必記與陷阱", "常見判讀與治療陷阱"],
  ["8. BWPS 表格 **漏掉 HR 130–139**，且 precipitant footnote 指錯 table。", "8. BWPS tachycardia scoring 中，**HR 130–139 為 20 分**。"],
  ["11. **Lithium 劑量在原不一致**，不可直接形成 order。", "11. **Lithium 僅作 specialist-guided alternative**，使用前須確認劑量及 target concentration。"],
  ["\u003e **版本與用藥安全提醒：**以下完整整合原章內容，用於急診專科考試與章節學習。原章包含數個內部劑量不一致、表格缺欄及可能受年代或地區可用性限制的藥物，不能直接視為現行 order set；實際使用須核對最新院內 protocol、藥物 availability 與專科建議。", "\u003e **用藥安全：**部分劑量與藥物可用性受年代與地區影響；實際處置應依最新院內 protocol、藥典與內分泌／毒物專科建議確認。"],
  ["疑似 intracranial hemorrhage 或 head trauma：先補 factor，再做 CT。****", "疑似 intracranial hemorrhage 或 head trauma：先補 factor，再做 CT。"],
  ["不是一般局部皮疹，而是可能因**呼吸道黏膜剝離、感染、低血容量、電解質與蛋白流失、DIC、休克及多器官衰竭**而致命的廣泛性皮膚疾病。正文詳述 erythema multiforme、SJS/TEN、pemphigus vulgaris、exfoliative dermatitis、DRESS、meningococcemia 與 purpura fulminans；表格另納入 staphylococcal/streptococcal toxic shock syndrome 與 staphylococcal scalded skin syndrome。", "廣泛性皮膚疾病可能因**呼吸道黏膜剝離、感染、低血容量、電解質與蛋白流失、DIC、休克及多器官衰竭**而致命；重要鑑別包括 erythema multiforme、SJS/TEN、pemphigus vulgaris、exfoliative dermatitis、DRESS、meningococcemia、purpura fulminans、toxic shock syndrome 與 staphylococcal scalded skin syndrome。"],
  ["章首雖提到 disseminated viral infections、Rocky Mountain spotted fever、disseminated gonococcal infection，但目前沒有其獨立診斷或治療段落，而是轉介其他章節；因此以下不補入章外細節。", ""],
  ["**Nikolsky sign 並非 TEN 專屬。**本TEN、pemphigus vulgaris 與 SSSS 均可呈陽性", "**Nikolsky sign 並非 TEN 專屬。**TEN、pemphigus vulgaris 與 SSSS 均可呈陽性"],
  ["這套流程必須依 hemodynamic status 解讀。正文也提到 FAST 有腹腔液體時 CT 可協助判斷後續傷勢，但**持續不穩定病人不能為了 CT 延誤止血**；CT 適用於穩定或經初始復甦後已有足夠反應者。", "這套流程必須依 hemodynamic status 解讀。FAST 有腹腔液體且病人已穩定或對初始復甦有足夠反應時，CT 可協助判斷後續傷勢；**持續不穩定病人不能為了 CT 延誤止血。**"],
  ["**範圍提醒**：並未詳細討論 septic arthritis、重大外傷性 fracture/dislocation 或 shoulder arthroplasty complication。若有發燒與 hot swollen joint、明顯外傷變形，或人工關節相關疼痛，不能直接套用保守治療路徑。", "發燒合併 hot swollen joint、明顯外傷變形或人工關節相關疼痛時，應優先排除 septic arthritis、重大 fracture/dislocation 與 arthroplasty complication，不能直接套用保守治療路徑。"],
  ["**第一是安全。**Aggressive 或 violent patient 可能需要 verbal de-escalation、physical restraint 或 chemical sedation；具體執行方式屬 Chapter 287 範圍。", "**第一是安全。**Aggressive 或 violent patient 可能需要 verbal de-escalation、physical restraint 或 chemical sedation，並應採最低限制且能維持安全的介入。"],
  ["| 暴力形式 | 章節涵蓋內容 |", "| 暴力形式 | 定義與臨床表現 |"],
  ["臨床上曾使用 *morbid obesity* 一詞，但**沒有另外提供一個通用的「病態性肥胖 BMI 定義」**，不應自行補上一個未列出的 cutoff。Bariatric surgery 術後併發症另見第 87 章。", "臨床評估不應只依 *morbid obesity* 標籤，而應結合 BMI、airway／ventilation、mobility、equipment limits 與 obesity-related complications。"],
  ["歷史背景資料指出，自 1980 年以來全球肥胖增加逾一倍；2008 年有超過 14 億名 20 歲以上成人過重，其中超過 2 億名男性與近 3 億名女性肥胖；2010 年則有超過 4,000 萬名 5 歲以下兒童過重。", ""],
];
